### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by OIQuinn** [lshtm-gis/WHO_PHSM_Cleaning#27]
"remains in place." in the comments should be coded as 10 - not of interest

previous examples:
"no new policy"

**Comment by OIQuinn** [comment]
"no changes observed." and "no changes reported." also new in the comments

**Comment by OIQuinn** [comment]
"no updates recorded"

**Comment by OIQuinn** [comment]
"no changes observed here."

**Comment by hamishgibbs** [comment]
Do these begin with capitals as most of the current ones seem to or are they as you have written?

**Comment by hamishgibbs** [comment]
Thanks! Added these and possible variants to the config. #86
