### ISSUE TITLE
non_compliance_penalty values

### ISSUE THREAD

**Issue by hamishgibbs** [lshtm-gis/WHO_PHSM_Cleaning#3]
For non_compliance_penalty can values of "not available" be set to blank, and "Refusal to enter the country" be set to "Refused entry to country"?

**Comment by hamishgibbs** [comment]
This has been added in the current processing routine. Still needs to be added in this repo.

**Comment by hamishgibbs** [comment]
Also seeing the issue of many possible capitalisations of the coded values, as if people have been typing in the values manually. 

In this repo - should add a check that columns only contain the accepted values - with proper capitalisation/punctuation etc.

**Comment by OIQuinn** [comment]
We went through and ensured all cells where in lower case. We may need to add this as one of our checks each week, at least for the first few weeks.

Below may also need revisiting:
if non_comp_penalty = Required, set to blank (new value from Oxford)
if non_comp_penalty = Refused entry to country set to Refused entry (change in our permitted values)

**Comment by OIQuinn** [comment]
"not available" has returned. Should be changed to blank.

**Comment by OIQuinn** [comment]
a couple of "refused entry to country" in the records, we are now coding this as "refused entry"

**Comment by hamishgibbs** [comment]
This should be handled. Closing here.
