### ISSUE TITLE
Check admin_level

### ISSUE THREAD

**Issue by hamishgibbs** [lshtm-gis/WHO_PHSM_Cleaning#4]
The check where admin_level = other and area_covered = 'national' seems to have disappeared (should be set admin_level = national, area_covered = blank).  

Think it's CDC only.

**Comment by OIQuinn** [comment]
admin_level = blank on some new cdc records
example: CDC-ITF-CY-00049

**Comment by hamishgibbs** [comment]
* Need to add a check for area_covered = 'national', change area_covered to blank

**Comment by hamishgibbs** [comment]
Thanks @OIQuinn - just about to fix the first issue. For `CDC-ITF-CY-00049` I am seeing that is has an `admin_level` == 'state' in `release_2020_11_20.csv` and `master_2020_11_20.csv`.

**Comment by hamishgibbs** [comment]
Any idea where that admin_level value might have gone?

**Comment by OIQuinn** [comment]
No, but I suspect it would be similar to https://github.com/lshtm-gis/WHO_PHSM_Cleaning/issues/67#issue-748237078 where admin_level is set to "other" and area_covered is the name of the country.

**Comment by hamishgibbs** [comment]
Ok thanks - about to start on that one and I will be back

**Comment by hamishgibbs** [comment]
Addressed in #65 and mentioned in #67
