### ISSUE TITLE
small island countries/territories/areas set to other

### ISSUE THREAD

**Issue by OIQuinn** [lshtm-gis/WHO_PHSM_Cleaning#67]
several island regions admin_level set to "other" and area_covered set to the name of island

e.g.
CDC_ITF_142158
CDC_ITF_142188
CDC_ITF_142144

From what I've seen so far they are all CDC records.

**Comment by OIQuinn** [comment]
Noticed this cropping up in a few larger countries too, e.g. Bulgaria.

**Comment by OIQuinn** [comment]
Examples in Cyprus:
CDC_ITF_142084
CDC_ITF_142085
CDC_ITF_142083

**Comment by hamishgibbs** [comment]
@OIQuinn It looks to me like all of the not_cleansed cdc records have an area_covered identical to their country name.

**Comment by hamishgibbs** [comment]
I will go looking for what is causing this.

**Comment by hamishgibbs** [comment]
Alright - CDC doesn’t provide any subnational information but country names were being mapped to two column (releasing a fix soon). 

they have a flag where admin_level = ‘Subnational/regional only’. This should be set to either other or state

**Comment by hamishgibbs** [comment]
We should manually remove any records in the mistress where country_territory_area == area_covered before processing again.

**Comment by hamishgibbs** [comment]
This is a CDC bug which should be handled with manual changes last week. Closing here.
