### ISSUE TITLE
Standardise country names

### ISSUE THREAD

**Issue by hamishgibbs** [lshtm-gis/WHO_PHSM_Cleaning#72]
Manually check that the master dataset does not have >1 string identifying a country.

**Comment by hamishgibbs** [comment]
@OIQuinn do you mean that we should try to identify that a record is actually national if it has a string that identifies the same country but in the `area_covered` column?

This seems difficult to me because the Czech Republic is not identical to Czechia and identifying that they are actually referring to the same place may be unreliable. If it is a small number of records this may be best handled by manual cleaning. What do you think?

**Comment by hamishgibbs** [comment]
Unrelated to that issue - we have the following country name conflicts in the country_territory_area_column.

`Bolivia, Plurinational state Of` and `Bolivia, Plurinational State Of`

`Democratic People's Republic Of Korea` and `Democratic People'S Republic Of Korea`

`United states Of America` and `United States Of America`

`Micronesia, Federated states Of` and `Micronesia, Federated States Of`

`Lao People's Democratic Republic` and `Lao People'S Democratic Republic`

The only difficult one is here:

`Pakistan` and `India` are both labelled as `iso` == `IND`. My assumption is that this is a small group of records where someone changed the country name but no the iso code. Changing the iso code to `PAK` should resolve this.

**Comment by hamishgibbs** [comment]
These steps should be done manually - I can do them before processing the mistress.

**Comment by OIQuinn** [comment]
I think in this instance you're correct, it may be easier to manually clean. After checking the link etc I could see that it was a national measure.

**Comment by OIQuinn** [comment]
Pakistan/India sounds like it was labelled as India and moved to Pakistan. Do you have a date processed for those records. I can check with the volunteer who cleaned them and inform them of the hidden columns etc.

**Comment by OIQuinn** [comment]
Is this a difference from the providers or is this a change from master to mistress?

**Comment by hamishgibbs** [comment]
Ok - about the change of India to Pakistan, I don't think it is a big deal as it is a single record: `CDC-ITF-IN-00083`. It will be easy for you or I to change and seems like a one-off. 

I have added the automated check for one-to-one relationships in #81 which will flag this type of thing in the future.

**Comment by OIQuinn** [comment]
Okay. I'll take a quick look. It might just be a new and keen volunteer changing it without realising there was more to change in the hidden columns. 
Are all the other columns correct? 
`who_region` and `iso_31661_numeric`

**Comment by OIQuinn** [comment]
When was this identified? The record that we gave to the volunteers this week is correct.

**Comment by hamishgibbs** [comment]
Ok - perhaps was fixed before. Not to worry. I will flag it if it appears in the mistress but is easy to fix.

**Comment by hamishgibbs** [comment]
Just addressed some of the issues with different country names in #87

**Comment by hamishgibbs** [comment]
This is also addressed in a new output check for multiple countries / numeric ISOs / who regions for a given ISO code.

**Comment by hamishgibbs** [comment]
Closing.
