### ISSUE TITLE
Target to be removed

### ISSUE THREAD

**Issue by OIQuinn** [lshtm-gis/WHO_PHSM_Cleaning#79]
"geographic subpopulation" in the target column, all JH records. 

Example IDs: 
JH_HIT_141929
JH_HIT_141947
JH_HIT_141948

**Comment by OIQuinn** [comment]
"entire population" in the target column, all JH records.

Example IDs
JH_HIT_141938
JH_HIT_141930

**Comment by OIQuinn** [comment]
"General"

example id: `OXCGRT_188251`

**Comment by hamishgibbs** [comment]
Looks like some of these are still in place from previous weeks. Should they be removed with a find & replace in the master file?

**Comment by hamishgibbs** [comment]
These have now been removed from the newest data and previous weeks.
