### ISSUE TITLE
Remove no update comment records

### ISSUE THREAD

**Issue by OIQuinn** [lshtm-gis/WHO_PHSM_Cleaning#90]
"no change" (all lowercase) in comment section

example id:  `OXCGRT_180498`

**Comment by OIQuinn** [comment]
"no change in policy found" (all lowercase) in comment section

example id: `OXCGRT_180490`

**Comment by OIQuinn** [comment]
" no change in policy" (all lowercase) in comment section

example id: `OXCGRT_180489`

**Comment by OIQuinn** [comment]
"No policy updates.    " + link

example id: `OXCGRT_182223`

**Comment by OIQuinn** [comment]
"The policy stays unchanged:    " + comment

example id: `OxCGRT_28544`

**Comment by hamishgibbs** [comment]
These have been added and will now be coded as who_code == "13". Thanks!
